# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

##########################################################################################
# Be sure to edit the values below
##########################################################################################

title: "Beta.ADA.gov"
# url: "https://example.gov" # the base hostname & protocol for your site, e.g. https://example.com.
# Required to support the jekyll-sitemap plugin below.
# Uncomment the url line when ready to push to production. If using different branches for multiple
# custom domains, edit this url parameter in the relevant branch to match the relevant custom domain.
description: Disability rights are civil rights. From voting to parking, the ADA is a law that protects people with disabilities in many areas of public life.

contact:
  tollfree: 800-514-0301
  tty: 800-514-0383
  link: /infoline/
  link_title: ADA Information Line

# Display beta disclamers
beta: true

# Digital Analytics Program (DAP) configuration
dap:
  agency: DOJ

# Configuration for Google Analytics
ga:
  ua: G-XXQSTBSHEN
google_site_verification: 34Ks265Uibpdda984RS0SxVABVZCdlVrdSp61pIdZQ8

# Site Navigation
primary_navigation:
  - name:
      en: Home
      es: Página principal
    url:
      en: "/"
      es: "/"
  - name:
      en: Topics
      es: Temas
    url:
      en: "/topics/"
      es: "/topics/"
  - name:
      en: Laws & Regulations
      es: Leyes y reglamentos
    url:
      en: "/law-and-regs/"
      es: "/law-and-regs/"
  - name:
      en: File a Complaint
      es: Presente una queja
    url:
      en: "/file-a-complaint/"
      es: "/es/presente-una-queja/"
  - name:
      en: Cases
      es: Casos
    url:
      en: "/cases/"
      es: "/cases/"
  - name:
      en: Give Us Feedback
      es: Denos su opinión
    url:
      en: https://touchpoints.app.cloud.gov/touchpoints/73c5715c/submit
      es: https://touchpoints.app.cloud.gov/touchpoints/73c5715c/submit
    external: true

# Collections
collections_dir: _pages
collections:
  topics:
    output: true
    permalink: /:collection/:name/
    sort_by: card.title
    order:
      - intro-to-ada.md
      - service-animals.md
      - parking.md
  news:
    item:
        title: Mobility Devices
        description: Some people with disabilities use mobility devices to get around, such as walkers, wheelchairs, or other power-driven devices. People with disabilities may use a variety of mobility devices based on their needs.
        permalink: /topics/mobility-devices/
    item2:
        title: Accessible Parking Spaces
        description: Accessible parking spaces are different than traditional parking spaces. They have specific features that make it easier for people with disabilities to access programs, goods, or services. The ADA requires businesses, non-profits, and state/local governments to provide accessible parking spaces.
        permalink: /topics/parking/
    item3:
        title: Service Animals
        description: The ADA explains what businesses and state/local governments must do to make sure that they do not discriminate against a member of the public with a disability who uses a service animal. Generally, service animals must be allowed to go most places where the public can go. Service animals can be any breed and any size of dog. Service animals are trained to perform a task directly related to a person's disability.
        permalink: /topics/service-animals/
    item4:
        title: File a Complaint
        description: "The Americans with Disabilities Act provides an important tool to fight discrimination: filing a complaint with an appropriate federal agency.  This page outlines the steps to get you started."
        permalink: /file-a-complaint/
# Configuration for Touchpoints
touchpoints:
  url: https://touchpoints.app.cloud.gov/touchpoints/73c5715c/submit

# Search.gov configuration
#
# 1. Create an account with Search.gov https://search.usa.gov/signup
# 2. Add a new site.
# 3. Add your site/affiliate name here.
searchgov:
  # You should not change this.
  endpoint: https://search.usa.gov

  # replace this with your search.gov account
  affiliate: justice-ada-beta

  # replace with your access key
  access_key: R9JA5YunOBaTGydUNm-oJjGCqKQ-zXsulsNskJVe5-c=

  # this renders the results within the page instead of sending to user to search.gov
  inline: true

  # how many results to display per pages
  limit: 20

##########################################################################################
# The values below here are more advanced and should only be
# changed if you know what they do
##########################################################################################

kramdown:
  parse_block_html: true

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      image:
        asset: default-card.png
      layout: "page"
      sidenav: true
      featured: false

languages: ["en"]
default_lang: "en"
exclude_from_localization: ["assets"]
parallel_localization: true

include:
  - _pages

exclude:
  - package.json
  - package-lock.json
  - README.md
  - CONTRIBUTING.md
  - LICENSE.md
  - Dockerfile
  - docker-compose.yml

assets:
  autoprefixer:
    browsers:
      - "> 2%"
      - "last 2 versions"
      - "IE 11"
      - "not dead"
  raw_precompile:
    - source: node_modules/uswds/dist/fonts/**/*
      strip: node_modules/uswds/dist/
    - source: node_modules/uswds/dist/img/sprite.svg
      strip: node_modules/uswds/dist/
  sources:
    - node_modules/anchor-js
    - node_modules/gumshoejs/dist
    - node_modules/uswds/dist
