version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@4.2.1

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
    steps:
      - checkout
      - node/install-packages
      - ruby/install-deps
      - run: npm run test:ci
      - store_artifacts:
          path: ./pa11y-results

workflows:
  commit:
    jobs:
      - test
